# Generated by Django 3.0.2 on 2020-01-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=48)),
                ('mail', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=258)),
                ('delete', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
