# Generated by Django 3.0.2 on 2020-01-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200111_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='delete',
            new_name='isdelete',
        ),
    ]
